# Generated by Django 2.2.1 on 2019-05-27 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fregistro', models.DateField(default=django.utils.timezone.now)),
                ('fhregistro', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fhmodificacion', models.DateTimeField(default=None, null=True)),
                ('descripcion', models.CharField(default=None, max_length=200)),
            ],
            options={
                'verbose_name': 'Alertas',
                'ordering': ['-fhregistro'],
                'get_latest_by': ['-fhregistro'],
            },
        ),
        migrations.CreateModel(
            name='Distritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fregistro', models.DateField(default=django.utils.timezone.now)),
                ('fhregistro', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fhmodificacion', models.DateTimeField(default=None, null=True)),
                ('descripcion', models.CharField(default=None, max_length=200)),
                ('ubigeo', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('latitud', models.CharField(default=None, max_length=200)),
                ('longitud', models.CharField(default=None, max_length=200)),
                ('provincia', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('departamento', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Distritos',
                'ordering': ['-fhregistro'],
                'get_latest_by': ['-fhregistro'],
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fregistro', models.DateField(default=django.utils.timezone.now)),
                ('fhregistro', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fhmodificacion', models.DateTimeField(default=None, null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Estados',
                'ordering': ['fhregistro'],
                'get_latest_by': ['fhregistro'],
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fregistro', models.DateField(default=django.utils.timezone.now)),
                ('fhregistro', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fhmodificacion', models.DateTimeField(default=None, null=True)),
                ('descripcion', models.CharField(default=None, max_length=200)),
                ('hora_desde', models.TimeField(default=django.utils.timezone.now)),
                ('hora_hasta', models.TimeField(default=django.utils.timezone.now)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recogedor.Estados')),
                ('username', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('username_modif', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recogedor_horarios_username_modif_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horarios',
                'ordering': ['-fhregistro'],
                'get_latest_by': ['-fhregistro'],
            },
        ),
        migrations.CreateModel(
            name='TipoReclamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fregistro', models.DateField(default=django.utils.timezone.now)),
                ('fhregistro', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fhmodificacion', models.DateTimeField(default=None, null=True)),
                ('descripcion', models.CharField(default=None, max_length=200)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recogedor.Estados')),
                ('username', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('username_modif', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recogedor_tiporeclamo_username_modif_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo Reclamo',
                'ordering': ['-fhregistro'],
                'get_latest_by': ['-fhregistro'],
            },
        ),
        migrations.CreateModel(
            name='PuntosAcopio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fregistro', models.DateField(default=django.utils.timezone.now)),
                ('fhregistro', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fhmodificacion', models.DateTimeField(default=None, null=True)),
                ('descripcion', models.CharField(default=None, max_length=200)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recogedor.Estados')),
                ('horarios', models.ManyToManyField(blank=True, help_text='Horarios especificos por P.Acopio.', to='recogedor.Horarios', verbose_name='Horarios por Punto de Acopio')),
                ('username', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('username_modif', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recogedor_puntosacopio_username_modif_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Puntos Acopio',
                'ordering': ['-fhregistro'],
                'get_latest_by': ['-fhregistro'],
            },
        ),
        migrations.AddIndex(
            model_name='estados',
            index=models.Index(fields=['descripcion'], name='recogedor_e_descrip_80931e_idx'),
        ),
        migrations.AddField(
            model_name='distritos',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recogedor.Estados'),
        ),
        migrations.AddField(
            model_name='distritos',
            name='username',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='distritos',
            name='username_modif',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recogedor_distritos_username_modif_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertas',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recogedor.Estados'),
        ),
        migrations.AddField(
            model_name='alertas',
            name='username',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertas',
            name='username_modif',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recogedor_alertas_username_modif_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tiporeclamo',
            index=models.Index(fields=['descripcion'], name='recogedor_t_descrip_1ca330_idx'),
        ),
        migrations.AddIndex(
            model_name='tiporeclamo',
            index=models.Index(fields=['fregistro'], name='recogedor_t_fregist_854322_idx'),
        ),
        migrations.AddIndex(
            model_name='tiporeclamo',
            index=models.Index(fields=['fhregistro'], name='recogedor_t_fhregis_b54dba_idx'),
        ),
        migrations.AddIndex(
            model_name='tiporeclamo',
            index=models.Index(fields=['fhmodificacion'], name='recogedor_t_fhmodif_9c1900_idx'),
        ),
        migrations.AddIndex(
            model_name='puntosacopio',
            index=models.Index(fields=['descripcion'], name='recogedor_p_descrip_d99ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='puntosacopio',
            index=models.Index(fields=['fregistro'], name='recogedor_p_fregist_d30140_idx'),
        ),
        migrations.AddIndex(
            model_name='puntosacopio',
            index=models.Index(fields=['fhregistro'], name='recogedor_p_fhregis_de991a_idx'),
        ),
        migrations.AddIndex(
            model_name='puntosacopio',
            index=models.Index(fields=['fhmodificacion'], name='recogedor_p_fhmodif_90cab7_idx'),
        ),
        migrations.AddIndex(
            model_name='horarios',
            index=models.Index(fields=['descripcion'], name='recogedor_h_descrip_f01915_idx'),
        ),
        migrations.AddIndex(
            model_name='horarios',
            index=models.Index(fields=['fregistro'], name='recogedor_h_fregist_b0c026_idx'),
        ),
        migrations.AddIndex(
            model_name='horarios',
            index=models.Index(fields=['fhregistro'], name='recogedor_h_fhregis_99e917_idx'),
        ),
        migrations.AddIndex(
            model_name='horarios',
            index=models.Index(fields=['fhmodificacion'], name='recogedor_h_fhmodif_13d654_idx'),
        ),
        migrations.AddIndex(
            model_name='horarios',
            index=models.Index(fields=['hora_desde'], name='recogedor_h_hora_de_97d147_idx'),
        ),
        migrations.AddIndex(
            model_name='horarios',
            index=models.Index(fields=['hora_hasta'], name='recogedor_h_hora_ha_2213c5_idx'),
        ),
        migrations.AddIndex(
            model_name='distritos',
            index=models.Index(fields=['descripcion'], name='recogedor_d_descrip_916e50_idx'),
        ),
        migrations.AddIndex(
            model_name='distritos',
            index=models.Index(fields=['fregistro'], name='recogedor_d_fregist_02a394_idx'),
        ),
        migrations.AddIndex(
            model_name='distritos',
            index=models.Index(fields=['fhregistro'], name='recogedor_d_fhregis_d153df_idx'),
        ),
        migrations.AddIndex(
            model_name='distritos',
            index=models.Index(fields=['fhmodificacion'], name='recogedor_d_fhmodif_f35736_idx'),
        ),
        migrations.AddIndex(
            model_name='distritos',
            index=models.Index(fields=['ubigeo'], name='recogedor_d_ubigeo_7748ae_idx'),
        ),
        migrations.AddIndex(
            model_name='distritos',
            index=models.Index(fields=['provincia'], name='recogedor_d_provinc_e43fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='distritos',
            index=models.Index(fields=['departamento'], name='recogedor_d_departa_e04041_idx'),
        ),
        migrations.AddIndex(
            model_name='alertas',
            index=models.Index(fields=['descripcion'], name='recogedor_a_descrip_b49ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='alertas',
            index=models.Index(fields=['fregistro'], name='recogedor_a_fregist_2856d6_idx'),
        ),
        migrations.AddIndex(
            model_name='alertas',
            index=models.Index(fields=['fhregistro'], name='recogedor_a_fhregis_06174a_idx'),
        ),
        migrations.AddIndex(
            model_name='alertas',
            index=models.Index(fields=['fhmodificacion'], name='recogedor_a_fhmodif_98c6ac_idx'),
        ),
    ]
